### ISSUE TITLE
weex creaet awesome-app issue

### ISSUE THREAD

**Issue by KitYeungDev** [weexteam/article#186]
I am a freshman for weex . Pls help to advise below error . Thanks .

**Environment :** 
Linux CentOS7 64bit
nodejs version : 8.9.4
npm version : 5.6.0

**Log :** 
module.js:540
    throw err;
    ^

Error: Cannot find module './gituser'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/itadgz/.xtoolkit/node_modules/weexpack/lib/utils/index.js:15:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by KitYeungDev** [comment]
er... fixed .

solution : 
```shell
cd /home/itadgz/.xtoolkit/node_modules/weexpack/lib/utils/
mv gitUser.js gituser.js
```
